- name: Linux post installation
  hosts: localhost
  connection: local
  roles:
    - apt_install
    - default_shell
    - role: default_shell
      user: root
    - ohmyzsh_install
    - zshrc_config
    - ohmyzsh_plugins_install
    - vundle_install
    - vimrc_config
    - home_bin_install
